language: node_js
node_js:
  - "7.10.1"
  - "8"
  - "node"
env:
  - NODE_ENV=test
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run coverage && codecov
  - npm run build:api
after_script: greenkeeper-lockfile-upload
cache:
  directories:
    - $HOME/.npm
