version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - NODE_ENV: TEST
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm version
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run coverage
      - run: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
